drop table kwery_user;

create table kwery_user (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  first_name varchar(255) not null,
  middle_name varchar(255),
  last_name varchar(255) not null,
  email varchar(1024) not null,
  password varchar(255) not null,
  created bigint not null,
  updated bigint,
  primary key (id),
  unique(email)
);

alter table job add column created bigint;
alter table job add column updated bigint;
