alter table kwery_user add column super_user boolean;

update kwery_user set super_user = true where id = (select id from kwery_user order by created asc fetch first row only);

create table installation_detail (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  installation_epoch bigint not null
);
