create table report_email_configuration (
  id integer generated by default as identity (start with 100, increment by 1),
  logo_url varchar(2083) not null,
  created bigint not null,
  updated bigint not null
);
