--Auto id columns start with 100 to prevent id collision as in this thread http://stackoverflow.com/questions/37410841/the-statement-was-aborted-because-it-would-have-caused-a-duplicate-key
--We insert ids with values for tests

create table kwery_user (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  password varchar(255) not null,
  username varchar(255) not null,
  primary key (id)
);

create table datasource (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  label varchar(255) not null,
  password varchar(255),
  port integer not null check (port>=1),
  type varchar(255),
  url varchar(255) not null,
  username varchar(255) not null,
  primary key (id)
);

create table query_run (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  cron_expression varchar(255),
  label varchar(255) not null,
  query varchar(255) not null,
  datasource_id_fk integer not null,
  primary key (id)
);

create table query_run_execution (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  execution_end bigint,
  execution_id varchar(255),
  execution_start bigint,
  result long varchar,
  status varchar(255),
  query_run_id_fk integer,
  primary key (id)
);

create table query_run_dependent (
  query_run_id_fk integer,
  dependent_query_run_id_fk integer,
  primary key (query_run_id_fk, dependent_query_run_id_fk)
);

create table smtp_configuration (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  host varchar(1024),
  port int,
  ssl boolean,
  username varchar(1024),
  password varchar(1024),
  primary key (id)
);

create table email_configuration (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  reply_to varchar(1024),
  bcc varchar(1024),
  primary key (id)
);

alter table kwery_user add constraint uc_kwery_user_username  unique (username);

alter table datasource add constraint uc_datasource_label  unique (label);

alter table query_run add constraint uc_query_run_label  unique (label);

alter table query_run add constraint fk_query_run_datasource_fk_id foreign key (datasource_id_fk) references datasource;

alter table query_run_execution add constraint fk_query_run_execution_query_run_id_fk foreign key (query_run_id_fk) references query_run;

alter table query_run_dependent add constraint fk_query_run_dependent_query_run_id_fk foreign key (query_run_id_fk) references query_run;
alter table query_run_dependent add constraint fk_query_run_dependent_dependent_query_run_id_fk foreign key (dependent_query_run_id_fk) references query_run;
