create table job_label (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  label varchar(255) not null,
  parent_label_id_fk integer,
  primary key (id)
);

alter table job_label add constraint fk_job_label_parent_label_id_fk foreign key (parent_label_id_fk) references job_label;
alter table job_label add constraint uc_job_label_label unique (label);

insert into job_label(label) select label from job;

alter table job drop constraint uc_job_label;
alter table job drop column label;

create table job_job_label (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  job_id_fk integer not null,
  job_label_id_fk integer not null,
  primary key (id)
);

alter table job_job_label add constraint fk_job_job_label_job_id_fk foreign key (job_id_fk) references job;
alter table job_job_label add constraint fk_job_job_label_job_label_id_fk foreign key (job_label_id_fk) references job_label;
alter table job_job_label add constraint uc_job_job_label_job_id_fk_job_label_id_fk unique (job_id_fk, job_label_id_fk);
