alter table smtp_configuration add column use_local_setting boolean;
update smtp_configuration set use_local_setting=false;

create table url_configuration (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  scheme varchar(5) not null,
  domain varchar(253) not null,
  port integer not null check (port>=1),
  primary key (id)
);

create table job_failure_alert_email (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  job_id_fk integer,
  email varchar(256),
  unique (job_id_fk, email)
);

alter table job_failure_alert_email add constraint fk_job_failure_alert_email_job_id_fk foreign key (job_id_fk) references job;

create table sql_query_email_setting (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  email_body_include boolean not null,
  email_attachment_include boolean not null,
  primary key (id)
);

create table sql_query_sql_query_email_setting (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  sql_query_id_fk integer not null constraint fk_sql_query_sql_query_email_setting_sql_query_id_fk references sql_query,
  sql_query_email_setting_id_fk integer not null CONSTRAINT fk_sql_query_sql_query_email_setting_sql_query_email_setting_id_fk references sql_query_email_setting,
  primary key (id),
  unique(sql_query_id_fk, sql_query_email_setting_id_fk)
);

