alter table smtp_configuration add column use_local_setting boolean;

create table url_configuration (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  scheme varchar(5) not null,
  domain varchar(253) not null,
  port integer not null check (port>=1),
  primary key (id)
);

create table job_failure_alert_email (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  job_id_fk integer,
  email varchar(256),
  unique (job_id_fk, email)
);

alter table job_failure_alert_email add constraint fk_job_failure_alert_email_job_id_fk foreign key (job_id_fk) references job;
