create table jjob_rule (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  sequential_sql_query_execution boolean not null,
  stop_execution_on_sql_query_failure boolean not null,
  primary key (id)
);

create table job_job_rule (
  id integer generated by default as identity (START WITH 100, INCREMENT BY 1),
  job_id_fk integer not null constraint fk_job_job_rule_job_id_fk references job,
  job_rule_id_fk integer not null constraint fk_job_job_rule_job_rule_id_fk references jjob_rule,
  primary key (id),
  unique(job_id_fk, job_rule_id_fk)
);
